#!/bin/sh
set -e

PACKAGE_NAME=pytestemb-lib

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p $PACKAGE_NAME
else
	dpkg -L $PACKAGE_NAME | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section